# ============================================================
# testing/Dockerfile.test - Imagen de pruebas NyxOS
# ============================================================
FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    qemu-system-x86 \
    qemu-kvm \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /iso

CMD ["/bin/bash"]