# ============================================================
# testing/Dockerfile - Entorno de compilación NyxOS
# ============================================================
FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV NYX_ROOT=/nyx-os

RUN apt-get update && apt-get install -y \
    build-essential \
    nasm \
    gcc-multilib \
    g++-multilib \
    grub-pc-bin \
    grub-common \
    xorriso \
    mtools \
    cpio \
    gzip \
    qemu-system-x86 \
    qemu-kvm \
    git \
    wget \
    curl \
    python3 \
    python3-pip \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /nyx-os
COPY . .

RUN chmod +x tools/build.sh

CMD ["/bin/bash"]